### PR TITLE
Adding #contains? method to polygons to determine if a coordinate is …

### PR DESCRIPTION
**Pull request by schrockwell**
…within its bounds

I added a basic test case, as well.

I also added some undeclared variables in `#centroid`.

### CODE REVIEW

**Comment by sethdeckard** [comment]
First off thanks for the contribution, I appreciate it.

I think I took a bit of a wrong turn adding `centroid` to the `Polygon` class. In fact I'm not longer even using this library in the project I added that specifically method for and I think it should probably be removed or at least marked as depreciated.

Rather than continuing down the path of adding additional geospatial methods to `Polygon`, I think it would be better if `Polygon` simply exposed a `to_wkt` method that returned the polygon formatted into [well-known text](https://en.wikipedia.org/wiki/Well-known_text).

This would then allow anyone to use whatever geospatial library they want (such as RGeo) since all of them allow you to easily parse WKT into their native object model. You'd then have a huge amount of geospatial operations you could perform on it, including the two mentioned here. It would also help if you're persisting the data into a database since WKT is used by PostGIS and other geospatial database implementations.

**Comment by schrockwell** [comment]
That is a great point – better to rely on the proven libraries to do what they do best. Seems like the WKT transformation would be pretty straightforward. 

The only thing I'm not so certain about is a polygon that straddles the international date line (± 180° longitude); you might have to detect and basically unwrap the phase of something like that. Or maybe the other libraries take that into account already?

Regardless, I'll close out this PR. Thanks for taking a look.

**Comment by schrockwell** [comment]
Want me to take a stab at a `to_wkt` implementation?

**Comment by sethdeckard** [comment]
Thanks for understanding and closing the PR. 

Providing a WKT formatted polygon is extremely straightforward, you don't have to do any kind of conversions or calculations on the coordinate data at all. The only gotcha (if you could call it that) is that WKT orders coordinates with longitude first (ex: Longitude, Latitude), which is reverse of what you're normally used to seeing outside of GIS applications but if you're thinking in more general terms of (X, Y) then the order actually does make sense because we're not necessarily always dealing with geographical coordinates in WKT. In fact the the polygons in the CAP XML put out by NWS will have the coordinates in the opposite order of WKT.

> The only thing I'm not so certain about is a polygon that straddles the international date line (± 180° longitude); you might have to detect and basically unwrap the phase of something like that. Or maybe the other libraries take that into account already?

It shouldn't matter, this new method should preserve the data as is regardless of any scenarios like this. Basically, the consumer using a geospatial library will set the appropriate projection when they parse the WTK, in this case the projection is known upfront since all NOAA/NWS polygons use WGS84.

> Want me to take a stab at a to_wkt implementation?

I hope I didn't come across as asking you to take that on but if you are willing I would appreciate it. As you suggested, it is really straight forward, just a matter of formatting the source data a little differently.

**Pull request closed without merging**
