### PR TITLE
Adding Polygon#to_wkt method for geospatial libraries

### PR DESCRIPTION
**Pull request by schrockwell**
Not much to say here. I tested the output locally with the GeoRuby gem.

### CODE REVIEW

**Comment by sethdeckard** [comment]
Thanks!

**Comment by schrockwell** [comment]
Glad to help. For my application, I ended up using the UGC county codes for checking locations anyway, since severe weather watches don't have polygons. :(

I just noticed there was a dev branch – should I have added the PR on that branch? (I'm still getting the hang of PRs.)

**Comment by sethdeckard** [comment]
You did fine, that dev branch was old and not really being used.

I noticed you had some extra whitespace and long lines in the files, the extra whitespace can be annoying for people who navigate via keyboard with text editors like Vim.

Not sure what editor you're using but you may be able to configure it to trim unnecessary whitespace or at least have it show you unnecessary whitespace as warnings. You also might be able to have it display a vertical line so you don't go over 80 chars on line length as well.

Finally, you can use Rubocop to run on the project (or just the file) and tell you about warnings like this, although it will tell you much more and not everything should always be addressed. You may be able to integrate that with your editor like I have with Vim here: 
screen shot 2016-07-26 at 8 48 13 am

**Comment by schrockwell** [comment]
Great thanks. I noticed the CI warnings above, but not sure what I could do besides close out the PR and submit another? Seems like a pain.

I'm on Sublime 3, and it looks like there is a RuboCop package. Will check it out.

**Comment by sethdeckard** [comment]
I think you can just push additional commits on that same branch created for the PR. Honestly never done it myself but I have seen others do it for the same reason on another repo of mine.

**Comment by schrockwell** [comment]
Makes sense. Thanks for your time and your gem!

**Comment by sethdeckard** [comment]
Thank you for the contribution. I also just bumped the version on the gem.

**Pull request merged**
